# This YAML file contains secret objects,
# which are necessary to run csi cinder plugin.


kind: Secret
apiVersion: v1
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cloud.conf: {{ printf "[Global]\nusername = %s\npassword = %s\ndomain-name = %s\nauth-url = %s\ntenant-name = %s\nregion = %s\n" .Values.username .Values.password .Values.domainName .Values.authUrl .Values.tenantName .Values.region | b64enc }}
